# Site settings
title: Canon
client:
  name: Canon
  link: https://www.canon.de/
description: >
  Im Urlaub erleben wir die Zeit anders als im Alltag. Mit allen Sinnen gewinnen wir neue Eindrücke und genießen die Begegnungen mit Mensch und Natur. Damit Ihr Urlaubsgefühl nicht in Vergessenheit gerät, unterstützt Sie Canon dabei, Ihre Geschichten in ausdruckstarken Bildern festzuhalten. Es erwarten Sie hier spannende Tipps & Tricks der Canon Academy Experten. Als besonderes Geschenk dürfen Sie sich einen 100GB Gutschein für die Canon irista Fotocloud mitnehmen.  
baseurl: "/canon" # the subpath of your site, e.g. /blog/
url: "http://mp.secretescapes.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [js/scripts.min.js]
sass:
    sass_dir: css
    style: compressed